[project]
name = "finam_core"
version = "1.0.0"
requires-python = ">=3.11"

dependencies = [
    "psycopg[binary]>=3.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]